addons:
  apt:
    packages:
    - python-pygments
install:
- gem install asciidoctor
- mkdir -p public
- rm -rf public || exit 0
script:
- bin/hugo
deploy:
  provider: s3
  access_key_id: AKIAIDEVIT2T435GVFWQ
  secret_access_key:
    secure: ta4Ziqa6yKvh3UpNW4fdyGDAxCTudGSQur4SKNvXQwS8R+QQ1JG2yyQrCFSNoTqr/wzf8/Ct4BssfD5PTbDo1fn9vfGXsOkQDdGjZnbDOpcijZutZx5JI4l+L3NMt8Q07qmGXMuXgKs/70Bsh4fHlCIwqlfDgqhKKqA5ASDj1ZtwOrMVStTGKGXIcBtFx0fDUVY011WBpJzUKzeOWvTLtIp3snwQrHhhuLORsnkCnkoVGq5t8gT/NpoJ68ikmrB6cgt0ayKhxjSqM3KXf6q837YPx3q5f7PFosBm1mYlAU6OSlnsxhKhB8jd2BkgWqQaYQ0gy4BEsJ0OcRMZAEiFGIZv/ailBJaK4gzp1yZJ+cE2zS5WXQXKjb2xHAThvSRCLo8ek1aIq/WDYIqXjaa0OxjfN8RpIj7RF7KP5M7JJ8vBKWJW45FJfkUV2cRLyKc3P2WyJZMIFnS4k9JX1OciLbHTpDA2paZnMwxUv3vCGGDP+ud/aZUmOMByU9nnRBv6kAYonT6fDswkeRsANvKPiv1pszZ+bGT8nx7oGOsALFIEAxaYCrxd7lOwXbjDl+z0fQUN4fzoDWx5JRIEe0D0cIbSZfVsX0XOUUjSflpEoOwMGP2DeuE1wpGtMTavTh2/1h2V3+wjhljksL7AMlMU3WBZAFGlzRAajSt2qx1NAwU=
  bucket: coffee.etsauer.com
  region: us-east-1
  local-dir: public
  acl: public_read
  on:
    repo: etsauer/coffee-site
